# Generated by Django 3.2.3 on 2021-06-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.CharField(max_length=200),
        ),
    ]
